parameters:
    kod3r_log.request_processor.class: Kod3r\LogBundle\Processor\RequestProcessor
    kod3r_log.logger_database.class: Kod3r\LogBundle\Logger\DatabaseHandler
    kod3r_log.logger_backtrace.class: Kod3r\LogBundle\EventListener\BacktraceLoggerListener
    kod3r_log.logger_utils.class: Kod3r\LogBundle\Utils\LoggerUtils

services:
    # Procesador de parametros de la peticion que se ejecutó
    kod3r_log.processor.request:
        class: %kod3r_log.request_processor.class%
        arguments: [@session]
        tags:
            - { name: monolog.processor, method: processRecord, channel: backtrace }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    #
    # Manejador de logs para el almacenamiento en Base de Datos
    # Este es el servicio que permite el almacenamiento de los logs en la Base de Datos
    kod3r_log.logger_database:
        class: %kod3r_log.logger_database.class%
        calls:
            - [ setEntityManager, [@doctrine.orm.entity_manager] ]

    #
    # Listener to record kernel events into logger system
    kod3r_log.logger_backtrace.listener:
        class: %kod3r_log.logger_backtrace.class%
        arguments:
            - @logger
            - @security.token_storage
        tags:
            - { name: monolog.logger, channel: backtrace }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    # Custom extension for random strings
    kod3r_log.twig.extension:
        class: Kod3r\LogBundle\Twig\Extension\JsonDecodeExtension
        tags:
            - { name: twig.extension }
