language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - nightly

matrix:
  allow_failures:
    - php: 5.5

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=dev-master

install: php vendor/vendors.php

before_script:
  - composer self-update
  - composer require symfony/http-foundation:${SYMFONY_VERSION}

notifications:
  email:
    - web.kod3r@gmail.com