language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: hhvm
    - env: SYMFONY_VERSION=2.8.*@dev
    #- env: SYMFONY_VERSION="3.0.x-dev as 2.8"

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=dev-master

#install: php vendor/vendors.php

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  #- composer global require phpunit/phpunit --no-update
  #- if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

notifications:
  email:
    - web.kod3r@gmail.com